### ISSUE TITLE
Non initialized vision_tower weights when loading HF teowu/llava_v1.5_7b_qinstruct_preview_v0.1

### ISSUE THREAD

**Issue by theAdamColton** [Q-Future/Q-Instruct#1]
I get this warning message when running the CLI script for the qinstruct llava 7B model:

```
Some weights of the model checkpoint at teowu/llava_v1.5_7b_qinstruct_preview_v0.1 were not used when initializing LlavaLlamaForCausalLM:
...
```
It then lists all of the weights for the model.vision_tower

I am running the cli inference code from LLaVa, using the qinstruct huggingface model:

```
python -m llava.serve.cli \
    --model-path teowu/llava_v1.5_7b_qinstruct_preview_v0.1 \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --load-4bit
```

This is after installing LLaVA from it's git repository

```
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
pip install -e .
```

The model still produces reasonable outputs, and it seems like it can accurately describe the image it was given. I just want to make sure that this warning message is expected

**Comment by teowu** [comment]
Yes, this warning does not affect the results. It loads weights from the pre-trained CLIPVisionTower (in huggingface transformers), which is not updated during training.
