### ISSUE TITLE
Have you tested your LLaVA1.5 in some traditional tasks, e.g., VQAv2?

### ISSUE THREAD

**Issue by HenryHZY** [Q-Future/Q-Instruct#3]
Hi @teowu, thanks for your great project.
We all know that LLaVA 1.5 is a bit slow for downstream tasks. And I would like to ask if you have tested your LLaVA1.5 in some traditional tasks, e.g., VQAv2?
If not, I can download the provided checkpoint to run some experiments:)

**Comment by teowu** [comment]
Truly. LLaVA-v1.5 is the slowest among the three.

It is okay to test in traditional high-level tasks, yet due to the dense fine-tuning of Q-Instruct, the checkpoints as provided might experience reduced performance on traditional high-level tasks.

**Comment by HenryHZY** [comment]
> due to the dense fine-tuning of Q-Instruct, the checkpoints as provided might experience reduced performance on traditional high-level tasks

Got it. I think this insight might be correct. I will try it later. Thank you.
