### ISSUE TITLE
About IQA evaluation code

### ISSUE THREAD

**Issue by Qiulin-W** [Q-Future/Q-Instruct#4]
Hi,

Great work!  I'm not clear about the evaluation code, "eval_image_quality.py", why line 61 is commented？What is the real prompt that is fed to the model?

![1701225586060](https://github.com/Q-Future/Q-Instruct/assets/37483535/2e5d3185-1c49-4976-b307-f12a47e9dfb7)

Thanks in advance!

**Comment by teowu** [comment]
The prompt starting "The image quality is" is not used here. After Q-Instruct, the result will only be slightly different either with or without the prompt starting.

You may try on both ways (or other prompt startings). 😏

**Comment by Qiulin-W** [comment]
> The prompt starting "The image quality is" is not used here. After Q-Instruct, the result will only be slightly different either with or without the prompt starting.
> 
> You may try on both ways (or other prompt startings). 😏

Any insight here? Why the prompt can be discarded?

**Comment by teowu** [comment]
The **prompt** (i.e. User Input) is actually the `qs`, i.e. `args.query`.
The "prompt starting" is like a condition (something like, telling MLLM that: you already output "The quality of the image is", then predict what the next word is). This is pretty useful for un-tuned MLLMs but not so effective with Q-Instruct (MLLMs are already prone to give simple single word outputs).
